name: Shadow Walker Actions
on:
  push:
    branches: [master]
  schedule:
  - cron: '0 0 * * *'
jobs:
  Shadow-Walker-Actions:
    runs-on: ubuntu-latest
    steps:
    - run: echo "🚀 shadow walker actions"
    - run: python3 --version
    - uses: actions/checkout@v3
    - run: python3 sitemap-parser/sitemap-parse.py > post.md
    - uses: actions/upload-artifact@v3
      with:
        name: posts
        path: post.md